#Library yang digunakan

In [ ]:
import numpy as np

Soal 1: Buatlah Tensor di bawah ini dengan Python:

In [ ]:
Tensor = np.array([[[23, 50],[7, 12]],
                  [[57, 67],[99, 43]],
                  [[75, 21],[57, 12]],
                  [[57, 12],[87, 26]]])

Tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[57, 12],
        [87, 26]]])

In [ ]:
Tensor.shape

(4, 2, 2)

Soal 2: Lakukan Perkalian Terhadap Matrix berikut:

In [ ]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])

B = np.array([17,22,19])

print(A)

print(B)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[17 22 19]


In [8]:
C = A*B

print(C)

[[ 391 1100  361]
 [ 119  264 2071]
 [ 969 1474 1862]]


Soal 3: Lakukan Transpose, Hitung Determinan dan Inverse terhadap Matrix di bawah ini:

In [9]:
D = np.array([[23, 50, 19],[7, 12, 109],[57, 67, 98]])

print(D)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


In [10]:
#Transpose

DTrans = D.T

D.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [11]:
#Determinant

DDet = np.linalg.det(D)

print(DDet)

131344.0000000002


In [12]:
#Invers

DInv = np.linalg.inv(D)

print(DInv)

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
